auto-update: true
record-durations:
    GOLD_RECORD: 178
    GREEN_RECORD: 185
    RECORD_3: 345
    RECORD_4: 185
    RECORD_5: 174
    RECORD_6: 197
    RECORD_7: 96
    RECORD_8: 150
    RECORD_9: 188
    RECORD_10: 251
    RECORD_11: 71
    RECORD_12: 235
